###############################################################################
# OpenVAS Vulnerability Test
# $Id: gb_nmap_http_enum_net.nasl 8087 2017-12-12 13:12:04Z teissa $
#
# Autogenerated NSE wrapper
#
# Authors:
# NSE-Script: Ron Bowes, Andrew Orr, Rob Nicholls
# NASL-Wrapper: autogenerated
#
# Copyright:
# NSE-Script: The Nmap Security Scanner (http://nmap.org)
# Copyright (C) 2011 Greenbone Networks GmbH, http://www.greenbone.net
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# (or any later version), as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
###############################################################################

tag_summary = "Enumerates directories used by popular web applications and servers.

This parses a fingerprint file that's formatted in a way that's compatible with the Nikto Web
application scanner. This script, however, takes it one step further by building in advanced pattern
matching as well as having the ability to identify specific versions of Web applications.

Currently, the database can be found under Nmap's directory in the nselib/data folder. The file is
called http-fingerprints and has a long description of its functionality in the file header.

Many of the finger prints were discovered by me (Ron Bowes), and a number of them are from the
Yokoso project, used with permission from Kevin Johnson (http://seclists.org/nmap-
dev/2009/q3/0685.html).

Initially, this script attempts to access two different random files in order to detect servers that
don't return a proper 404 Not Found status. In the event that they return 200 OK, the body has any
non-static-looking data removed (URI, time, etc), and saved. If the two random attempts return
different results, the script aborts (since a 200-looking 404 cannot be distinguished from an actual
200). This will prevent most false positives.

In addition, if the root folder returns a 301 Moved Permanently or 401 Authentication Required,
this script will also abort. If the root folder has disappeared or requires authentication, there is
little hope of finding anything inside it.

By default, only pages that return 200 OK or 401 Authentication Required are displayed. If the <code
>http-enum.displayall' script argument is set, however, then all results will be displayed
(except for 404 Not Found and the status code returned by the random files). Entries in the http-
fingerprints database can specify their own criteria for accepting a page as valid.




SYNTAX:

http-enum.basepath:          The base path to prepend to each request. Leading/trailing slashes are ignored. 


http.pipeline:  If set, it represents the number of HTTP requests that'll be
pipelined (ie, sent in a single request). This can be set low to make
debugging easier, or it can be set high to test how a server reacts (its
chosen max is ignored).


http.useragent:  The value of the User-Agent header field sent with
requests. By default it is
''Mozilla/5.0 (compatible; Nmap Scripting Engine; http://nmap.org/book/nse.html)''.
A value of the empty string disables sending the User-Agent header field.



http-enum.category:          Set to a category (as defined in the fingerprints file). Some options are 'attacks',
'database', 'general', 'microsoft', 'printer', etc.



http-enum.displayall:        Set this argument to display all status codes that may indicate a valid page, not
just 200 OK and 401 Authentication Required pages. Although this is more likely
to find certain hidden folders, it also generates far more false positives. 


http-max-cache-size:  The maximum memory size (in bytes) of the cache.";

if(description)
{
    script_oid("1.3.6.1.4.1.25623.1.0.104159");
    script_version("$Revision: 8087 $");
    script_tag(name:"last_modification", value:"$Date: 2017-12-12 14:12:04 +0100 (Tue, 12 Dec 2017) $");
    script_tag(name:"creation_date", value:"2011-06-01 16:32:46 +0200 (Wed, 01 Jun 2011)");
    script_tag(name:"cvss_base", value:"5.0");
    script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:N/C:P/I:N/A:N");
    script_name("Nmap NSE net: http-enum");


    script_category(ACT_INIT);
    script_tag(name:"qod_type", value:"remote_analysis");
    script_copyright("NSE-Script: The Nmap Security Scanner; NASL-Wrapper: Greenbone Networks GmbH");
    script_family("Nmap NSE net");
    script_dependencies("nmap_nse_net.nasl");
    script_mandatory_keys("Tools/Launch/nmap_nse_net");

    script_add_preference(name:"http-enum.basepath", value:"", type:"entry");
    script_add_preference(name:"http.pipeline", value:"", type:"entry");
    script_add_preference(name:"http.useragent", value:"", type:"entry");
    script_add_preference(name:"http-enum.category", value:"", type:"entry");
    script_add_preference(name:"http-enum.displayall", value:"", type:"entry");
    script_add_preference(name:"http-max-cache-size", value:"", type:"entry");

    script_tag(name : "summary" , value : tag_summary);
    exit(0);
}


include("nmap.inc");

# The corresponding NSE script does't belong to the 'safe' category
if (safe_checks()) exit(0);

phase = 0;
if (defined_func("scan_phase")) {
    phase = scan_phase();
}

if (phase == 1) {
    # Get the preferences
    argv = make_array();

    pref = script_get_preference("http-enum.basepath");
    if (!isnull(pref) && pref != "") {
        argv["http-enum.basepath"] = string('"', pref, '"');
    }
    pref = script_get_preference("http.pipeline");
    if (!isnull(pref) && pref != "") {
        argv["http.pipeline"] = string('"', pref, '"');
    }
    pref = script_get_preference("http.useragent");
    if (!isnull(pref) && pref != "") {
        argv["http.useragent"] = string('"', pref, '"');
    }
    pref = script_get_preference("http-enum.category");
    if (!isnull(pref) && pref != "") {
        argv["http-enum.category"] = string('"', pref, '"');
    }
    pref = script_get_preference("http-enum.displayall");
    if (!isnull(pref) && pref != "") {
        argv["http-enum.displayall"] = string('"', pref, '"');
    }
    pref = script_get_preference("http-max-cache-size");
    if (!isnull(pref) && pref != "") {
        argv["http-max-cache-size"] = string('"', pref, '"');
    }
    nmap_nse_register(script:"http-enum", args:argv);
} else if (phase == 2) {
    res = nmap_nse_get_results(script:"http-enum");
    foreach portspec (keys(res)) {
        output_banner = 'Result found by Nmap Security Scanner (http-enum.nse) http://nmap.org:\n\n';
        if (portspec == "0") {
            security_message(data:output_banner + res[portspec], port:0);
        } else {
            v = split(portspec, sep:"/", keep:0);
            proto = v[0];
            port = v[1];
            security_message(data:output_banner + res[portspec], port:port, protocol:proto);
        }
    }
}
