###############################################################################
# OpenVAS Vulnerability Test
# $Id: gb_nmap_smtp_open_relay_net.nasl 8115 2017-12-14 07:30:22Z teissa $
#
# Autogenerated NSE wrapper
#
# Authors:
# NSE-Script: Arturo 'Buanzo' Busleiman
# NASL-Wrapper: autogenerated
#
# Copyright:
# NSE-Script: The Nmap Security Scanner (http://nmap.org)
# Copyright (C) 2011 Greenbone Networks GmbH, http://www.greenbone.net
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# (or any later version), as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
###############################################################################

tag_summary = "Attempts to relay mail by issuing a predefined combination of SMTP commands. The goal of this
script is to tell if a SMTP server is vulnerable to mail relaying.

An SMTP server that works as an open relay, is a email server that does not verify if the user is
authorised to send email from the specified email address. Therefore, users would be able to send
email originating from any third-party email address that they want.

The checks are done based in combinations of MAIL FROM and RCPT TO commands. The list is hardcoded
in the source file. The script will output all the working combinations that the server allows if
nmap is in verbose mode otherwise the script will print the number of successful tests. The script
will not output if the server requires authentication.

If debug is enabled and an error occurrs while testing the target host, the error will be printed
with the list of any combinations that were found prior to the error.


SYNTAX:

smtp-open-relay.ip:  Use this to change the IP address to be used (default is the target IP address)


smtp-open-relay.to:  Define the destination email address to be used (without the domain, default is
relaytest)


smtp-open-relay.from:  Define the source email address to be used (without the domain, default is
antispam)


smtp-open-relay.domain:  Define the domain to be used in the anti-spam tests and EHLO command (default
is nmap.scanme.org)";

if(description)
{
    script_oid("1.3.6.1.4.1.25623.1.0.104108");
    script_version("$Revision: 8115 $");
    script_tag(name:"last_modification", value:"$Date: 2017-12-14 08:30:22 +0100 (Thu, 14 Dec 2017) $");
    script_tag(name:"creation_date", value:"2011-06-01 16:32:46 +0200 (Wed, 01 Jun 2011)");
    script_tag(name:"cvss_base", value:"7.5");
    script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:N/C:P/I:P/A:P");
    script_name("Nmap NSE net: smtp-open-relay");


    script_category(ACT_INIT);
    script_tag(name:"qod_type", value:"remote_analysis");
    script_copyright("NSE-Script: The Nmap Security Scanner; NASL-Wrapper: Greenbone Networks GmbH");
    script_family("Nmap NSE net");
    script_dependencies("nmap_nse_net.nasl");
    script_mandatory_keys("Tools/Launch/nmap_nse_net");

    script_add_preference(name:"smtp-open-relay.ip", value:"", type:"entry");
    script_add_preference(name:"smtp-open-relay.to", value:"", type:"entry");
    script_add_preference(name:"smtp-open-relay.from", value:"", type:"entry");
    script_add_preference(name:"smtp-open-relay.domain", value:"", type:"entry");

    script_tag(name : "summary" , value : tag_summary);
    exit(0);
}


include("nmap.inc");

# The corresponding NSE script does't belong to the 'safe' category
if (safe_checks()) exit(0);

phase = 0;
if (defined_func("scan_phase")) {
    phase = scan_phase();
}

if (phase == 1) {
    # Get the preferences
    argv = make_array();

    pref = script_get_preference("smtp-open-relay.ip");
    if (!isnull(pref) && pref != "") {
        argv["smtp-open-relay.ip"] = string('"', pref, '"');
    }
    pref = script_get_preference("smtp-open-relay.to");
    if (!isnull(pref) && pref != "") {
        argv["smtp-open-relay.to"] = string('"', pref, '"');
    }
    pref = script_get_preference("smtp-open-relay.from");
    if (!isnull(pref) && pref != "") {
        argv["smtp-open-relay.from"] = string('"', pref, '"');
    }
    pref = script_get_preference("smtp-open-relay.domain");
    if (!isnull(pref) && pref != "") {
        argv["smtp-open-relay.domain"] = string('"', pref, '"');
    }
    nmap_nse_register(script:"smtp-open-relay", args:argv);
} else if (phase == 2) {
    res = nmap_nse_get_results(script:"smtp-open-relay");
    foreach portspec (keys(res)) {
        output_banner = 'Result found by Nmap Security Scanner (smtp-open-relay.nse) http://nmap.org:\n\n';
        if (portspec == "0") {
            security_message(data:output_banner + res[portspec], port:0);
        } else {
            v = split(portspec, sep:"/", keep:0);
            proto = v[0];
            port = v[1];
            security_message(data:output_banner + res[portspec], port:port, protocol:proto);
        }
    }
}
