###############################################################################
# OpenVAS Vulnerability Test
# $Id: gb_apache_hadoop_info_disclosure_vuln.nasl 6485 2017-06-29 09:21:18Z santu $
#
# Apache Hadoop 'MapReduce' Information Disclosure Vulnerability
#
# Authors:
# Kashinath T <tkashinath@secpod.com>
# 
# Copyright:
# Copyright (C) 2017 Greenbone Networks GmbH, http://www.greenbone.net
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# (or any later version), as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
###############################################################################

CPE = "cpe:/a:apache:hadoop";

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.0.811401");
  script_version("$Revision: 6485 $");
  script_cve_id("CVE-2015-1776");
  script_bugtraq_id(83259);
  script_tag(name:"cvss_base", value:"2.1");
  script_tag(name:"cvss_base_vector", value:"AV:L/AC:L/Au:N/C:P/I:N/A:N");
  script_tag(name:"last_modification", value:"$Date: 2017-06-29 11:21:18 +0200 (Thu, 29 Jun 2017) $");
  script_tag(name:"creation_date", value:"2017-06-27 20:31:53 +0530 (Tue, 27 Jun 2017)");
  script_name("Apache Hadoop 'MapReduce' Information Disclosure Vulnerability");

  script_tag(name:"summary", value:"The host is installed with Apache Hadoop
  and is prone to an information disclosure vulnerability.");

  script_tag(name:"vuldetect", value:"Get the installed version with the help
  of detect NVT and check the version is vulnerable or not.");

  script_tag(name:"insight", value:"The flaw exists due to apache hadoop encrypts
  intermediate data generated by a MapReduce job and stores it along with the
  encryption key in a credentials file on disk when the Intermediate data encryption
  feature is enabled.");

  script_tag(name:"impact", value:"Successful exploitation will allow local users to
  obtain sensitive information by reading the file.

  Impact Level: System/Application");

  script_tag(name:"affected", value:"All versions of Hadoop 2.6.x");

  script_tag(name:"solution", value:"Upgrade to Apache Hadoop version 2.7.x or
  later or disable the feature when running MapReduce jobs. 
  For updates refer to http://www.hadoop.apache.org");

  script_tag(name:"solution_type", value:"VendorFix");

  script_xref(name:"URL", value:"http://seclists.org/oss-sec/2016/q1/344");
  script_tag(name:"qod_type", value:"remote_banner_unreliable");
  script_copyright("Copyright (C) 2017 Greenbone Networks GmbH");
  script_category(ACT_GATHER_INFO);
  script_family("Web application abuses");
  script_dependencies("gb_apache_hadoop_detect.nasl");
  script_mandatory_keys("Apache/Hadoop/Installed");
  script_require_ports("Services/www", 50070);
  exit(0);
}

include("version_func.inc");
include("host_details.inc");

#Variable initialize
hadoopPort = "";
hadoopVer = "";

if(!hadoopPort = get_app_port(cpe:CPE)){
  exit(0);
}

## Get the version
if(!hadoopVer = get_app_version(cpe:CPE, port:hadoopPort)){
  exit(0);
}

## Checking for vulnerable version
if(hadoopVer =~ "^(2\.6)")
{
  report = report_fixed_ver(installed_version:hadoopVer, fixed_version:"2.7.X");
  security_message(data:report, port:hadoopPort);
  exit(0);
}
