###############################################################################
# OpenVAS Vulnerability Test
# $Id: gb_nmap6_smtp_open_relay.nasl 9364 2018-04-06 07:33:03Z cfischer $
#
# Autogenerated NSE wrapper
#
# Authors:
# NSE-Script: Arturo 'Buanzo' Busleiman
# NASL-Wrapper: autogenerated
#
# Copyright:
# NSE-Script: The Nmap Security Scanner (http://nmap.org)
# Copyright (C) 2013 Greenbone Networks GmbH, http://www.greenbone.net
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# (or any later version), as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
###############################################################################

tag_summary = "Attempts to relay mail by issuing a predefined combination of SMTP commands. The goal of this
script is to tell if a SMTP server is vulnerable to mail relaying.

An SMTP server that works as an open relay, is a email server that does not verify if the user is
authorised to send email from the specified email address. Therefore, users would be able to send
email originating from any third-party email address that they want.

The checks are done based in combinations of MAIL FROM and RCPT TO commands. The list is hardcoded
in the source file. The script will output all the working combinations that the server allows if
nmap is in verbose mode otherwise the script will print the number of successful tests. The script
will not output if the server requires authentication.

If debug is enabled and an error occurrs while testing the target host, the error will be printed
with the list of any combinations that were found prior to the error.


SYNTAX:

smtp-open-relay.ip:  Use this to change the IP address to be used (default is the target IP address)


smtp.domain:  or smtp-open-relay.domain Define the domain to be used in the anti-spam tests and EHLO command (default
is nmap.scanme.org)


smtp-open-relay.to:  Define the destination email address to be used (without the domain, default is
relaytest)


smtp-open-relay.from:  Define the source email address to be used (without the domain, default is
antispam)";

if(description)
{
    script_oid("1.3.6.1.4.1.25623.1.0.803526");
    script_version("$Revision: 9364 $");
    script_tag(name:"cvss_base", value:"7.5");
    script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:N/C:P/I:P/A:P");
    script_tag(name:"last_modification", value:"$Date: 2018-04-06 09:33:03 +0200 (Fri, 06 Apr 2018) $");
    script_tag(name:"creation_date", value:"2013-02-28 19:00:15 +0530 (Thu, 28 Feb 2013)");
    script_name("Nmap NSE 6.01: smtp-open-relay");


    script_category(ACT_ATTACK);
    script_tag(name:"qod_type", value:"remote_analysis");
    script_copyright("NSE-Script: The Nmap Security Scanner; NASL-Wrapper: Greenbone Networks GmbH");
    script_family("Nmap NSE");

    script_add_preference(name:"smtp-open-relay.ip", value:"", type:"entry");
    script_add_preference(name:"smtp.domain", value:"", type:"entry");
    script_add_preference(name:"smtp-open-relay.to", value:"", type:"entry");
    script_add_preference(name:"smtp-open-relay.from", value:"", type:"entry");

    script_dependencies("toolcheck.nasl");
    script_mandatory_keys("Tools/Present/nmap6.01");
    script_mandatory_keys("Tools/Launch/nmap_nse");

    script_tag(name : "summary" , value : tag_summary);
    exit(0);
}

# The corresponding NSE script doesn't belong to the 'safe' category
if (safe_checks()) exit(0);


# Get the preferences
i = 0;

## Get SMTP Ports
port = get_kb_item("Services/smtp");
if(!port){
  exit(0);
}

pref = script_get_preference("smtp-open-relay.ip");
if (!isnull(pref) && pref != "") {
  args[i++] = string('"', 'smtp-open-relay.ip', '=', pref, '"');
}
pref = script_get_preference("smtp.domain");
if (!isnull(pref) && pref != "") {
  args[i++] = string('"', 'smtp.domain', '=', pref, '"');
}
pref = script_get_preference("smtp-open-relay.to");
if (!isnull(pref) && pref != "") {
  args[i++] = string('"', 'smtp-open-relay.to', '=', pref, '"');
}
pref = script_get_preference("smtp-open-relay.from");
if (!isnull(pref) && pref != "") {
  args[i++] = string('"', 'smtp-open-relay.from', '=', pref, '"');
}

argv = make_list("nmap", "--script=smtp-open-relay.nse", "-p", port, get_host_ip());

if(i > 0)
{
  scriptArgs= "--script-args=";
  foreach arg(args) {
    scriptArgs += arg + ",";
  }
  argv = make_list(argv,scriptArgs);
}

## Run nmap and Get the Result
res = pread(cmd: "nmap", argv: argv);

if(res)
{
  foreach line (split(res))
  {
    if(ereg(pattern:"^\|",string:line)) {
      result +=  substr(chomp(line),2) + '\n';
    }

    error = eregmatch(string:line, pattern:"^nmap: (.*)$");
    if (error) {
      msg = string('Nmap command failed with following error message:\n', line);
      log_message(data : msg, port:port);
    }
  }

  if("smtp-open-relay" >< result) {
    msg = string('Result found by Nmap Security Scanner (smtp-open-relay.nse) ',
                'http://nmap.org:\n\n', result);
    security_message(data : msg, port:port);
  }
}
else
{
  msg = string('Nmap command failed entirely:\n', 'nmap ', argv);
  log_message(data: msg, port:port);
}
